package bmbsoft.orderfoodonline.entities;
// Generated Sep 18, 2018 12:33:50 AM by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Attribute generated by hbm2java
 */
@Entity
@Table(name = "attribute", catalog = "ofo")
public class Attribute implements java.io.Serializable {

	private Long atributeId;
	private AttributeGroup attributeGroup;
	private ContentDefinition contentDefinition;
	private String code;
	private Integer isStatus;
	private Set<RestaurantAttribute> restaurantAttributes = new HashSet<RestaurantAttribute>(0);

	public Attribute() {
	}

	public Attribute(AttributeGroup attributeGroup, ContentDefinition contentDefinition) {
		this.attributeGroup = attributeGroup;
		this.contentDefinition = contentDefinition;
	}

	public Attribute(AttributeGroup attributeGroup, ContentDefinition contentDefinition, String code, Integer isStatus,
			Set<RestaurantAttribute> restaurantAttributes) {
		this.attributeGroup = attributeGroup;
		this.contentDefinition = contentDefinition;
		this.code = code;
		this.isStatus = isStatus;
		this.restaurantAttributes = restaurantAttributes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "atribute_id", unique = true, nullable = false)
	public Long getAtributeId() {
		return this.atributeId;
	}

	public void setAtributeId(Long atributeId) {
		this.atributeId = atributeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "attribute_group_id", nullable = false)
	public AttributeGroup getAttributeGroup() {
		return this.attributeGroup;
	}

	public void setAttributeGroup(AttributeGroup attributeGroup) {
		this.attributeGroup = attributeGroup;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "content_dep_id", nullable = false)
	public ContentDefinition getContentDefinition() {
		return this.contentDefinition;
	}

	public void setContentDefinition(ContentDefinition contentDefinition) {
		this.contentDefinition = contentDefinition;
	}

	@Column(name = "code")
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "is_status")
	public Integer getIsStatus() {
		return this.isStatus;
	}

	public void setIsStatus(Integer isStatus) {
		this.isStatus = isStatus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "attribute")
	public Set<RestaurantAttribute> getRestaurantAttributes() {
		return this.restaurantAttributes;
	}

	public void setRestaurantAttributes(Set<RestaurantAttribute> restaurantAttributes) {
		this.restaurantAttributes = restaurantAttributes;
	}

}
