package bmbsoft.orderfoodonline.entities;
// Generated Sep 18, 2018 12:33:50 AM by Hibernate Tools 5.2.10.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AttributeGroup generated by hbm2java
 */
@Entity
@Table(name = "attribute_group")
public class AttributeGroup implements java.io.Serializable {

	private Long attibuteGroupId;
	private ContentDefinition contentDefinition;
	private String code;
	private Integer status;
	private Date createdDate;
	private Set<Attribute> attributes = new HashSet<Attribute>(0);

	public AttributeGroup() {
	}

	public AttributeGroup(ContentDefinition contentDefinition, String code) {
		this.contentDefinition = contentDefinition;
		this.code = code;
	}

	public AttributeGroup(ContentDefinition contentDefinition, String code, Integer status, Date createdDate,
			Set<Attribute> attributes) {
		this.contentDefinition = contentDefinition;
		this.code = code;
		this.status = status;
		this.createdDate = createdDate;
		this.attributes = attributes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "attibute_group_id", unique = true, nullable = false)
	public Long getAttibuteGroupId() {
		return this.attibuteGroupId;
	}

	public void setAttibuteGroupId(Long attibuteGroupId) {
		this.attibuteGroupId = attibuteGroupId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "content_dep_id", nullable = false)
	public ContentDefinition getContentDefinition() {
		return this.contentDefinition;
	}

	public void setContentDefinition(ContentDefinition contentDefinition) {
		this.contentDefinition = contentDefinition;
	}

	@Column(name = "code", nullable = false)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "attributeGroup")
	public Set<Attribute> getAttributes() {
		return this.attributes;
	}

	public void setAttributes(Set<Attribute> attributes) {
		this.attributes = attributes;
	}

}
