package bmbsoft.orderfoodonline.entities;
// Generated Sep 18, 2018 12:33:50 AM by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ContentEntry generated by hbm2java
 */
@Entity
@Table(name = "content_entry", catalog = "ofo")
public class ContentEntry implements java.io.Serializable {

	private Long contentEntryId;
	private ContentDefinition contentDefinition;
	private Language language;
	private String code;
	private String value;

	public ContentEntry() {
	}

	public ContentEntry(ContentDefinition contentDefinition, Language language, String code, String value) {
		this.contentDefinition = contentDefinition;
		this.language = language;
		this.code = code;
		this.value = value;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "content_entry_id", unique = true, nullable = false)
	public Long getContentEntryId() {
		return this.contentEntryId;
	}

	public void setContentEntryId(Long contentEntryId) {
		this.contentEntryId = contentEntryId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "content_dep_id", nullable = false)
	public ContentDefinition getContentDefinition() {
		return this.contentDefinition;
	}

	public void setContentDefinition(ContentDefinition contentDefinition) {
		this.contentDefinition = contentDefinition;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "language_id", nullable = false)
	public Language getLanguage() {
		return this.language;
	}

	public void setLanguage(Language language) {
		this.language = language;
	}

	@Column(name = "code", nullable = false, length = 65535)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "value", nullable = false, length = 65535)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
