package bmbsoft.orderfoodonline.entities;
// Generated Sep 18, 2018 12:33:50 AM by Hibernate Tools 5.2.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CurrencyRate generated by hbm2java
 */
@Entity
@Table(name = "currency_rate")
public class CurrencyRate implements java.io.Serializable {

	private Long currencyRateId;
	private Currency currency;
	private String checksum;
	private Double rate;
	private Date updated;

	public CurrencyRate() {
	}

	public CurrencyRate(Currency currency) {
		this.currency = currency;
	}

	public CurrencyRate(Currency currency, String checksum, Double rate, Date updated) {
		this.currency = currency;
		this.checksum = checksum;
		this.rate = rate;
		this.updated = updated;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "currency_rate_id", unique = true, nullable = false)
	public Long getCurrencyRateId() {
		return this.currencyRateId;
	}

	public void setCurrencyRateId(Long currencyRateId) {
		this.currencyRateId = currencyRateId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "currency_id", nullable = false)
	public Currency getCurrency() {
		return this.currency;
	}

	public void setCurrency(Currency currency) {
		this.currency = currency;
	}

	@Column(name = "checksum", length = 200)
	public String getChecksum() {
		return this.checksum;
	}

	public void setChecksum(String checksum) {
		this.checksum = checksum;
	}

	@Column(name = "rate", precision = 12, scale = 2)
	public Double getRate() {
		return this.rate;
	}

	public void setRate(Double rate) {
		this.rate = rate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated", length = 19)
	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

}
