package bmbsoft.orderfoodonline.entities;
// Generated Aug 1, 2018 11:13:58 AM by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ExtraItem generated by hbm2java
 */
@Entity
@Table(name = "extra_item", catalog = "ofo_prod")
public class ExtraItem implements java.io.Serializable {

	private Long extraItemId;
	private ContentDefinition contentDefinition;
	private MenuExtraItem menuExtraItem;
	private Long price;

	public ExtraItem() {
	}

	public ExtraItem(MenuExtraItem menuExtraItem) {
		this.menuExtraItem = menuExtraItem;
	}

	public ExtraItem(ContentDefinition contentDefinition, MenuExtraItem menuExtraItem, Long price) {
		this.contentDefinition = contentDefinition;
		this.menuExtraItem = menuExtraItem;
		this.price = price;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "extra_item_id", unique = true, nullable = false)
	public Long getExtraItemId() {
		return this.extraItemId;
	}

	public void setExtraItemId(Long extraItemId) {
		this.extraItemId = extraItemId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "content_dep_id")
	public ContentDefinition getContentDefinition() {
		return this.contentDefinition;
	}

	public void setContentDefinition(ContentDefinition contentDefinition) {
		this.contentDefinition = contentDefinition;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "menu_extra_item_id", nullable = false)
	public MenuExtraItem getMenuExtraItem() {
		return this.menuExtraItem;
	}

	public void setMenuExtraItem(MenuExtraItem menuExtraItem) {
		this.menuExtraItem = menuExtraItem;
	}

	@Column(name = "price", precision = 10, scale = 0)
	public Long getPrice() {
		return this.price;
	}

	public void setPrice(Long price) {
		this.price = price;
	}

}
