package bmbsoft.orderfoodonline.entities;
// Generated Aug 1, 2018 11:13:58 AM by Hibernate Tools 5.2.10.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Language generated by hbm2java
 */
@Entity
@Table(name = "language", catalog = "ofo_prod")
public class Language implements java.io.Serializable {

	private Long languageId;
	private String name;
	private String code;
	private Integer status;
	private Date createdDate;
	private String createdBy;
	private Date modifiedDate;
	private String modifiedBy;
	private Set<ContentEmail> contentEmails = new HashSet<ContentEmail>(0);
	private Set<ContentEntry> contentEntries = new HashSet<ContentEntry>(0);
	private Set<LanguageResource> languageResources = new HashSet<LanguageResource>(0);

	public Language() {
	}

	public Language(String name, String code, Integer status, Date createdDate, String createdBy, Date modifiedDate,
			String modifiedBy, Set<ContentEmail> contentEmails, Set<ContentEntry> contentEntries,
			Set<LanguageResource> languageResources) {
		this.name = name;
		this.code = code;
		this.status = status;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.modifiedDate = modifiedDate;
		this.modifiedBy = modifiedBy;
		this.contentEmails = contentEmails;
		this.contentEntries = contentEntries;
		this.languageResources = languageResources;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "language_id", unique = true, nullable = false)
	public Long getLanguageId() {
		return this.languageId;
	}

	public void setLanguageId(Long languageId) {
		this.languageId = languageId;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "code")
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "created_by")
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modified_date", length = 19)
	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	@Column(name = "modified_by")
	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "language")
	public Set<ContentEmail> getContentEmails() {
		return this.contentEmails;
	}

	public void setContentEmails(Set<ContentEmail> contentEmails) {
		this.contentEmails = contentEmails;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "language")
	public Set<ContentEntry> getContentEntries() {
		return this.contentEntries;
	}

	public void setContentEntries(Set<ContentEntry> contentEntries) {
		this.contentEntries = contentEntries;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "language")
	public Set<LanguageResource> getLanguageResources() {
		return this.languageResources;
	}

	public void setLanguageResources(Set<LanguageResource> languageResources) {
		this.languageResources = languageResources;
	}

}
