package bmbsoft.orderfoodonline.entities;
// Generated Sep 18, 2018 12:33:50 AM by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MenuItem generated by hbm2java
 */
@Entity
@Table(name = "menu_item")
public class MenuItem implements java.io.Serializable {

	private Long menuItemId;
	private ContentDefinition contentDefinition;
	private Menu menu;
	private Long price;
	private String picturePath;
	private Boolean isCombo;
	private String urlSlug;
	private Integer sortOrder;
	private Integer isStatus;
	private Set<OrderLineItem> orderLineItems = new HashSet<OrderLineItem>(0);
	private Set<MenuExtraItem> menuExtraItems = new HashSet<MenuExtraItem>(0);

	public MenuItem() {
	}

	public MenuItem(ContentDefinition contentDefinition, Menu menu) {
		this.contentDefinition = contentDefinition;
		this.menu = menu;
	}

	public MenuItem(ContentDefinition contentDefinition, Menu menu, Long price, String picturePath, Boolean isCombo,
			String urlSlug, Integer sortOrder, Integer isStatus, Set<OrderLineItem> orderLineItems,
			Set<MenuExtraItem> menuExtraItems) {
		this.contentDefinition = contentDefinition;
		this.menu = menu;
		this.price = price;
		this.picturePath = picturePath;
		this.isCombo = isCombo;
		this.urlSlug = urlSlug;
		this.sortOrder = sortOrder;
		this.isStatus = isStatus;
		this.orderLineItems = orderLineItems;
		this.menuExtraItems = menuExtraItems;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "menu_item_id", unique = true, nullable = false)
	public Long getMenuItemId() {
		return this.menuItemId;
	}

	public void setMenuItemId(Long menuItemId) {
		this.menuItemId = menuItemId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "content_dep_id", nullable = false)
	public ContentDefinition getContentDefinition() {
		return this.contentDefinition;
	}

	public void setContentDefinition(ContentDefinition contentDefinition) {
		this.contentDefinition = contentDefinition;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "menu_id", nullable = false)
	public Menu getMenu() {
		return this.menu;
	}

	public void setMenu(Menu menu) {
		this.menu = menu;
	}

	@Column(name = "price", precision = 10, scale = 0)
	public Long getPrice() {
		return this.price;
	}

	public void setPrice(Long price) {
		this.price = price;
	}

	@Column(name = "picture_path")
	public String getPicturePath() {
		return this.picturePath;
	}

	public void setPicturePath(String picturePath) {
		this.picturePath = picturePath;
	}

	@Column(name = "is_combo")
	public Boolean getIsCombo() {
		return this.isCombo;
	}

	public void setIsCombo(Boolean isCombo) {
		this.isCombo = isCombo;
	}

	@Column(name = "url_slug")
	public String getUrlSlug() {
		return this.urlSlug;
	}

	public void setUrlSlug(String urlSlug) {
		this.urlSlug = urlSlug;
	}

	@Column(name = "sort_order")
	public Integer getSortOrder() {
		return this.sortOrder;
	}

	public void setSortOrder(Integer sortOrder) {
		this.sortOrder = sortOrder;
	}

	@Column(name = "is_status")
	public Integer getIsStatus() {
		return this.isStatus;
	}

	public void setIsStatus(Integer isStatus) {
		this.isStatus = isStatus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "menuItem")
	public Set<OrderLineItem> getOrderLineItems() {
		return this.orderLineItems;
	}

	public void setOrderLineItems(Set<OrderLineItem> orderLineItems) {
		this.orderLineItems = orderLineItems;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "menuItem")
	public Set<MenuExtraItem> getMenuExtraItems() {
		return this.menuExtraItems;
	}

	public void setMenuExtraItems(Set<MenuExtraItem> menuExtraItems) {
		this.menuExtraItems = menuExtraItems;
	}

}
