package bmbsoft.orderfoodonline.entities;
// Generated Aug 1, 2018 11:13:58 AM by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ModuleAction generated by hbm2java
 */
@Entity
@Table(name = "module_action", catalog = "ofo_prod")
public class ModuleAction implements java.io.Serializable {

	private long moduleActionId;
	private String moduleName;
	private String action;
	private String moduleDesc;
	private Set<RoleModule> roleModules = new HashSet<RoleModule>(0);

	public ModuleAction() {
	}

	public ModuleAction(long moduleActionId) {
		this.moduleActionId = moduleActionId;
	}

	public ModuleAction(long moduleActionId, String moduleName, String action, String moduleDesc,
			Set<RoleModule> roleModules) {
		this.moduleActionId = moduleActionId;
		this.moduleName = moduleName;
		this.action = action;
		this.moduleDesc = moduleDesc;
		this.roleModules = roleModules;
	}

	@Id

	@Column(name = "module_action_id", unique = true, nullable = false)
	public long getModuleActionId() {
		return this.moduleActionId;
	}

	public void setModuleActionId(long moduleActionId) {
		this.moduleActionId = moduleActionId;
	}

	@Column(name = "module_name")
	public String getModuleName() {
		return this.moduleName;
	}

	public void setModuleName(String moduleName) {
		this.moduleName = moduleName;
	}

	@Column(name = "action")
	public String getAction() {
		return this.action;
	}

	public void setAction(String action) {
		this.action = action;
	}

	@Column(name = "module_desc", length = 500)
	public String getModuleDesc() {
		return this.moduleDesc;
	}

	public void setModuleDesc(String moduleDesc) {
		this.moduleDesc = moduleDesc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "moduleAction")
	public Set<RoleModule> getRoleModules() {
		return this.roleModules;
	}

	public void setRoleModules(Set<RoleModule> roleModules) {
		this.roleModules = roleModules;
	}

}
