package bmbsoft.orderfoodonline.entities;
// Generated Jun 14, 2018 12:13:51 AM by Hibernate Tools 5.2.8.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OrderDelivery generated by hbm2java
 */
@Entity
@Table(name = "order_delivery", catalog = "ofo")
public class OrderDelivery implements java.io.Serializable {

	private long orderDeliveryId;
	private Order order;
	private String address;
	private String deliveryTime;
	private String remarks;
	private String city;
	private String district;

	public OrderDelivery() {
	}

	public OrderDelivery(long orderDeliveryId) {
		this.orderDeliveryId = orderDeliveryId;
	}

	public OrderDelivery(long orderDeliveryId, Order order, String address, String deliveryTime, String remarks,
			String city, String district) {
		this.orderDeliveryId = orderDeliveryId;
		this.order = order;
		this.address = address;
		this.deliveryTime = deliveryTime;
		this.remarks = remarks;
		this.city = city;
		this.district = district;
	}

	@Id

	@Column(name = "order_delivery_id", unique = true, nullable = false)
	public long getOrderDeliveryId() {
		return this.orderDeliveryId;
	}

	public void setOrderDeliveryId(long orderDeliveryId) {
		this.orderDeliveryId = orderDeliveryId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "order_id")
	public Order getOrder() {
		return this.order;
	}

	public void setOrder(Order order) {
		this.order = order;
	}

	@Column(name = "address")
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "delivery_time")
	public String getDeliveryTime() {
		return this.deliveryTime;
	}

	public void setDeliveryTime(String deliveryTime) {
		this.deliveryTime = deliveryTime;
	}

	@Column(name = "remarks", length = 65535)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	@Column(name = "city")
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "district")
	public String getDistrict() {
		return this.district;
	}

	public void setDistrict(String district) {
		this.district = district;
	}

}
