package bmbsoft.orderfoodonline.entities;
// Generated Sep 18, 2018 12:33:50 AM by Hibernate Tools 5.2.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OrderTransaction generated by hbm2java
 */
@Entity
@Table(name = "order_transaction")
public class OrderTransaction implements java.io.Serializable {

	private long orderTransactionId;
	private OrderPayment orderPayment;
	private Date createdDate;
	private String createdBy;
	private Integer status;
	private String transactionIdentifier;
	private Long amount;
	private String currencyCode;
	private String errorType;

	public OrderTransaction() {
	}

	public OrderTransaction(long orderTransactionId) {
		this.orderTransactionId = orderTransactionId;
	}

	public OrderTransaction(long orderTransactionId, OrderPayment orderPayment, Date createdDate, String createdBy,
			Integer status, String transactionIdentifier, Long amount, String currencyCode, String errorType) {
		this.orderTransactionId = orderTransactionId;
		this.orderPayment = orderPayment;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.status = status;
		this.transactionIdentifier = transactionIdentifier;
		this.amount = amount;
		this.currencyCode = currencyCode;
		this.errorType = errorType;
	}

	@Id

	@Column(name = "order_transaction_id", unique = true, nullable = false)
	public long getOrderTransactionId() {
		return this.orderTransactionId;
	}

	public void setOrderTransactionId(long orderTransactionId) {
		this.orderTransactionId = orderTransactionId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "order_payment_id")
	public OrderPayment getOrderPayment() {
		return this.orderPayment;
	}

	public void setOrderPayment(OrderPayment orderPayment) {
		this.orderPayment = orderPayment;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "created_by")
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "transaction_identifier")
	public String getTransactionIdentifier() {
		return this.transactionIdentifier;
	}

	public void setTransactionIdentifier(String transactionIdentifier) {
		this.transactionIdentifier = transactionIdentifier;
	}

	@Column(name = "amount", precision = 10, scale = 2)
	public Long getAmount() {
		return this.amount;
	}

	public void setAmount(Long amount) {
		this.amount = amount;
	}

	@Column(name = "currency_code", length = 10)
	public String getCurrencyCode() {
		return this.currencyCode;
	}

	public void setCurrencyCode(String currencyCode) {
		this.currencyCode = currencyCode;
	}

	@Column(name = "error_type", length = 65535)
	public String getErrorType() {
		return this.errorType;
	}

	public void setErrorType(String errorType) {
		this.errorType = errorType;
	}

}
