package bmbsoft.orderfoodonline.entities;
// Generated Sep 18, 2018 12:33:50 AM by Hibernate Tools 5.2.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OrderHistory generated by hbm2java
 */
@Entity
@Table(name = "order_history")
public class OrderHistory implements java.io.Serializable {

	private Long orderHisId;
	private String orderObj;
	private Date createdDate;

	public OrderHistory() {
	}

	public OrderHistory(String orderObj, Date createdDate) {
		this.orderObj = orderObj;
		this.createdDate = createdDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "order_his_id", unique = true, nullable = false)
	public Long getOrderHisId() {
		return this.orderHisId;
	}

	public void setOrderHisId(Long orderHisId) {
		this.orderHisId = orderHisId;
	}

	@Column(name = "order_obj", length = 65535)
	public String getOrderObj() {
		return this.orderObj;
	}

	public void setOrderObj(String orderObj) {
		this.orderObj = orderObj;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

}
