package bmbsoft.orderfoodonline.entities;
// Generated Sep 18, 2018 12:33:50 AM by Hibernate Tools 5.2.10.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OrderPayment generated by hbm2java
 */
@Entity
@Table(name = "order_payment", catalog = "ofo")
public class OrderPayment implements java.io.Serializable {

	private Long orderPaymentId;
	private Order order;
	private Integer orderPaymentType;
	private Date createdDate;
	private String createdBy;
	private Set<OrderTransaction> orderTransactions = new HashSet<OrderTransaction>(0);

	public OrderPayment() {
	}

	public OrderPayment(Order order) {
		this.order = order;
	}

	public OrderPayment(Order order, Integer orderPaymentType, Date createdDate, String createdBy,
			Set<OrderTransaction> orderTransactions) {
		this.order = order;
		this.orderPaymentType = orderPaymentType;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.orderTransactions = orderTransactions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "order_payment_id", unique = true, nullable = false)
	public Long getOrderPaymentId() {
		return this.orderPaymentId;
	}

	public void setOrderPaymentId(Long orderPaymentId) {
		this.orderPaymentId = orderPaymentId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "order_id", nullable = false)
	public Order getOrder() {
		return this.order;
	}

	public void setOrder(Order order) {
		this.order = order;
	}

	@Column(name = "order_payment_type")
	public Integer getOrderPaymentType() {
		return this.orderPaymentType;
	}

	public void setOrderPaymentType(Integer orderPaymentType) {
		this.orderPaymentType = orderPaymentType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "created_by")
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orderPayment")
	public Set<OrderTransaction> getOrderTransactions() {
		return this.orderTransactions;
	}

	public void setOrderTransactions(Set<OrderTransaction> orderTransactions) {
		this.orderTransactions = orderTransactions;
	}

}
