package bmbsoft.orderfoodonline.entities;
// Generated Sep 18, 2018 12:33:50 AM by Hibernate Tools 5.2.10.Final

import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * OrderExtraItem generated by hbm2java
 */
@Entity
@Table(name = "order_extra_item")
public class OrderExtraItem implements java.io.Serializable {

	private Long orderExtraItemId;
	private OrderLineItem orderLineItem;
	private Long menuItemId;
	private Long menuExtraItemId;
	private Long extraItemId;
	private Double unitPrice;
	private Double totalPrice;

	public OrderExtraItem() {
	}

	public OrderExtraItem(Long orderExtraItemId, OrderLineItem orderLineItem, Long menuItemId, Long menuExtraItemId, Long extraItemId, Double unitPrice, Double totalPrice) {
		this.orderExtraItemId = orderExtraItemId;
		this.orderLineItem = orderLineItem;
		this.menuItemId = menuItemId;
		this.menuExtraItemId = menuExtraItemId;
		this.extraItemId = extraItemId;
		this.unitPrice = unitPrice;
		this.totalPrice = totalPrice;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "order_extra_item_id", unique = true, nullable = false)
	public Long getOrderExtraItemId() {
		return this.orderExtraItemId;
	}

	public void setOrderExtraItemId(Long orderExtraItemId) {
		this.orderExtraItemId = orderExtraItemId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "order_line_item_id")
	public OrderLineItem getOrderLineItem() {
		return orderLineItem;
	}

	public void setOrderLineItem(OrderLineItem orderLineItem) {
		this.orderLineItem = orderLineItem;
	}

	@Column(name = "menu_item_id")
	public Long getMenuItemId() {
		return this.menuItemId;
	}

	public void setMenuItemId(Long menuItemId) {
		this.menuItemId = menuItemId;
	}

	@Column(name = "menu_extra_item_id")
	public Long getMenuExtraItemId() {
		return this.menuExtraItemId;
	}

	public void setMenuExtraItemId(Long menuExtraItemId) {
		this.menuExtraItemId = menuExtraItemId;
	}

	@Column(name = "extra_item_id")
	public Long getExtraItemId() {
		return this.extraItemId;
	}

	public void setExtraItemId(Long extraItemId) {
		this.extraItemId = extraItemId;
	}

	@Column(name = "unit_price", precision = 10, scale = 2)
	public Double getUnitPrice() {
		return this.unitPrice;
	}

	public void setUnitPrice(Double unitPrice) {
		this.unitPrice = unitPrice;
	}

	@Column(name = "total_price", precision = 10, scale = 2)
	public Double getTotalPrice() {
		return this.totalPrice;
	}

	public void setTotalPrice(Double totalPrice) {
		this.totalPrice = totalPrice;
	}

}
