package bmbsoft.orderfoodonline.entities;
// Generated Sep 18, 2018 12:33:50 AM by Hibernate Tools 5.2.10.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * OrderLineItem generated by hbm2java
 */
@Entity
@Table(name = "order_line_item")
public class OrderLineItem implements java.io.Serializable {

	private Long orderLineItemId;
	private MenuItem menuItem;
	private Order order;
	private Double unitPrice;
	private Integer quantity;
	private String createdBy;
	private Integer status;
	private String menuItemName;
	private Double discountTotal;
	private Double total;
	private Date createdDate;
	private Set<OrderExtraItem> orderExtraItems = new HashSet<>(0);
	public OrderLineItem() {
	}

	public OrderLineItem(Long orderLineItemId, MenuItem menuItem, Order order, Double unitPrice, Integer quantity, String createdBy, Integer status, String menuItemName, Double discountTotal, Double total, Date createdDate, Set<OrderExtraItem> orderExtraItems) {
		this.orderLineItemId = orderLineItemId;
		this.menuItem = menuItem;
		this.order = order;
		this.unitPrice = unitPrice;
		this.quantity = quantity;
		this.createdBy = createdBy;
		this.status = status;
		this.menuItemName = menuItemName;
		this.discountTotal = discountTotal;
		this.total = total;
		this.createdDate = createdDate;
		this.orderExtraItems = orderExtraItems;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "order_line_item_id", unique = true, nullable = false)
	public Long getOrderLineItemId() {
		return this.orderLineItemId;
	}

	public void setOrderLineItemId(Long orderLineItemId) {
		this.orderLineItemId = orderLineItemId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "menu_item_id")
	public MenuItem getMenuItem() {
		return this.menuItem;
	}

	public void setMenuItem(MenuItem menuItem) {
		this.menuItem = menuItem;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "order_id")
	public Order getOrder() {
		return this.order;
	}

	public void setOrder(Order order) {
		this.order = order;
	}

	@Column(name = "unit_price", precision = 10, scale = 2)
	public Double getUnitPrice() {
		return this.unitPrice;
	}

	public void setUnitPrice(Double unitPrice) {
		this.unitPrice = unitPrice;
	}

	@Column(name = "quantity")
	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	@Column(name = "created_by")
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "menu_item_name")
	public String getMenuItemName() {
		return this.menuItemName;
	}

	public void setMenuItemName(String menuItemName) {
		this.menuItemName = menuItemName;
	}

	@Column(name = "discount_total", precision = 10, scale = 2)
	public Double getDiscountTotal() {
		return this.discountTotal;
	}

	public void setDiscountTotal(Double discountTotal) {
		this.discountTotal = discountTotal;
	}

	@Column(name = "total", precision = 10, scale = 2)
	public Double getTotal() {
		return this.total;
	}

	public void setTotal(Double total) {
		this.total = total;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orderLineItem")
	public Set<OrderExtraItem> getOrderExtraItems() {
		return orderExtraItems;
	}

	public void setOrderExtraItems(Set<OrderExtraItem> orderExtraItems) {
		this.orderExtraItems = orderExtraItems;
	}
}
