package bmbsoft.orderfoodonline.entities;
// Generated Sep 18, 2018 12:33:50 AM by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * OrderExtraItem generated by hbm2java
 */
@Entity
@Table(name = "order_extra_item")
public class OrderExtraItem implements java.io.Serializable {

	private Long orderExtraItemId;
	private Long menuItemId;
	private Long menuExtraItemId;
	private Long exraItemId;
	private Double unitPrice;
	private Double totalPrice;

	public OrderExtraItem() {
	}

	public OrderExtraItem(Long menuItemId, Long menuExtraItemId, Long exraItemId, Double unitPrice, Double totalPrice) {
		this.menuItemId = menuItemId;
		this.menuExtraItemId = menuExtraItemId;
		this.exraItemId = exraItemId;
		this.unitPrice = unitPrice;
		this.totalPrice = totalPrice;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "order_extra_item_id", unique = true, nullable = false)
	public Long getOrderExtraItemId() {
		return this.orderExtraItemId;
	}

	public void setOrderExtraItemId(Long orderExtraItemId) {
		this.orderExtraItemId = orderExtraItemId;
	}

	@Column(name = "menu_item_id")
	public Long getMenuItemId() {
		return this.menuItemId;
	}

	public void setMenuItemId(Long menuItemId) {
		this.menuItemId = menuItemId;
	}

	@Column(name = "menu_extra_item_id")
	public Long getMenuExtraItemId() {
		return this.menuExtraItemId;
	}

	public void setMenuExtraItemId(Long menuExtraItemId) {
		this.menuExtraItemId = menuExtraItemId;
	}

	@Column(name = "exra_item_id")
	public Long getExraItemId() {
		return this.exraItemId;
	}

	public void setExraItemId(Long exraItemId) {
		this.exraItemId = exraItemId;
	}

	@Column(name = "unit_price", precision = 10, scale = 2)
	public Double getUnitPrice() {
		return this.unitPrice;
	}

	public void setUnitPrice(Double unitPrice) {
		this.unitPrice = unitPrice;
	}

	@Column(name = "total_price", precision = 10, scale = 2)
	public Double getTotalPrice() {
		return this.totalPrice;
	}

	public void setTotalPrice(Double totalPrice) {
		this.totalPrice = totalPrice;
	}

}
