package bmbsoft.orderfoodonline.entities;
// Generated Sep 18, 2018 12:33:50 AM by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OrderInfo generated by hbm2java
 */
@Entity
@Table(name = "order_info")
public class OrderInfo implements java.io.Serializable {

	private Long orderInfoId;
	private Order order;
	private String infoName;
	private String infoEmail;
	private String infoNumber;
	private String companyName;
	private String address;
	private String city;
	private String district;
	private String time;
	private String remark;
	private String addressDesc;

	public OrderInfo() {
	}

	public OrderInfo(Order order, String infoName, String infoEmail, String infoNumber, String companyName,
			String address, String city, String district, String time, String remark, String addressDesc) {
		this.order = order;
		this.infoName = infoName;
		this.infoEmail = infoEmail;
		this.infoNumber = infoNumber;
		this.companyName = companyName;
		this.address = address;
		this.city = city;
		this.district = district;
		this.time = time;
		this.remark = remark;
		this.addressDesc = addressDesc;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "order_info_id", unique = true, nullable = false)
	public Long getOrderInfoId() {
		return this.orderInfoId;
	}

	public void setOrderInfoId(Long orderInfoId) {
		this.orderInfoId = orderInfoId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "order_id")
	public Order getOrder() {
		return this.order;
	}

	public void setOrder(Order order) {
		this.order = order;
	}

	@Column(name = "info_name")
	public String getInfoName() {
		return this.infoName;
	}

	public void setInfoName(String infoName) {
		this.infoName = infoName;
	}

	@Column(name = "info_email")
	public String getInfoEmail() {
		return this.infoEmail;
	}

	public void setInfoEmail(String infoEmail) {
		this.infoEmail = infoEmail;
	}

	@Column(name = "info_number")
	public String getInfoNumber() {
		return this.infoNumber;
	}

	public void setInfoNumber(String infoNumber) {
		this.infoNumber = infoNumber;
	}

	@Column(name = "company_name")
	public String getCompanyName() {
		return this.companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	@Column(name = "address")
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "city")
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "district")
	public String getDistrict() {
		return this.district;
	}

	public void setDistrict(String district) {
		this.district = district;
	}

	@Column(name = "time")
	public String getTime() {
		return this.time;
	}

	public void setTime(String time) {
		this.time = time;
	}

	@Column(name = "remark")
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "address_desc")
	public String getAddressDesc() {
		return this.addressDesc;
	}

	public void setAddressDesc(String addressDesc) {
		this.addressDesc = addressDesc;
	}

}
