package bmbsoft.orderfoodonline.entities;
// Generated Sep 18, 2018 12:33:50 AM by Hibernate Tools 5.2.10.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PaymentProvider generated by hbm2java
 */
@Entity
@Table(name = "payment_provider")
public class PaymentProvider implements java.io.Serializable {

	private Long paymentProviderId;
	private String name;
	private String setting;
	private Date createdDate;
	private String createdBy;
	private Date modifiedDate;
	private String modifiedBy;
	private Integer isStatus;
	private Integer sortOrder;
	private Set<RestaurantPaymentProvider> restaurantPaymentProviders = new HashSet<RestaurantPaymentProvider>(0);

	public PaymentProvider() {
	}

	public PaymentProvider(String name, String setting) {
		this.name = name;
		this.setting = setting;
	}

	public PaymentProvider(String name, String setting, Date createdDate, String createdBy, Date modifiedDate,
			String modifiedBy, Integer isStatus, Integer sortOrder,
			Set<RestaurantPaymentProvider> restaurantPaymentProviders) {
		this.name = name;
		this.setting = setting;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.modifiedDate = modifiedDate;
		this.modifiedBy = modifiedBy;
		this.isStatus = isStatus;
		this.sortOrder = sortOrder;
		this.restaurantPaymentProviders = restaurantPaymentProviders;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "payment_provider_id", unique = true, nullable = false)
	public Long getPaymentProviderId() {
		return this.paymentProviderId;
	}

	public void setPaymentProviderId(Long paymentProviderId) {
		this.paymentProviderId = paymentProviderId;
	}

	@Column(name = "name", nullable = false, length = 200)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "setting", nullable = false, length = 65535)
	public String getSetting() {
		return this.setting;
	}

	public void setSetting(String setting) {
		this.setting = setting;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "created_by")
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modified_date", length = 19)
	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	@Column(name = "modified_by")
	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Column(name = "is_status")
	public Integer getIsStatus() {
		return this.isStatus;
	}

	public void setIsStatus(Integer isStatus) {
		this.isStatus = isStatus;
	}

	@Column(name = "sort_order")
	public Integer getSortOrder() {
		return this.sortOrder;
	}

	public void setSortOrder(Integer sortOrder) {
		this.sortOrder = sortOrder;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "paymentProvider")
	public Set<RestaurantPaymentProvider> getRestaurantPaymentProviders() {
		return this.restaurantPaymentProviders;
	}

	public void setRestaurantPaymentProviders(Set<RestaurantPaymentProvider> restaurantPaymentProviders) {
		this.restaurantPaymentProviders = restaurantPaymentProviders;
	}

}
