package bmbsoft.orderfoodonline.entities;
// Generated Sep 18, 2018 12:33:50 AM by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PromotionLineitem generated by hbm2java
 */
@Entity
@Table(name = "promotion_lineitem", catalog = "ofo")
public class PromotionLineitem implements java.io.Serializable {

	private Long promotionLineitemId;
	private Promotion promotion;
	private Restaurant restaurant;
	private String code;

	public PromotionLineitem() {
	}

	public PromotionLineitem(Promotion promotion, Restaurant restaurant) {
		this.promotion = promotion;
		this.restaurant = restaurant;
	}

	public PromotionLineitem(Promotion promotion, Restaurant restaurant, String code) {
		this.promotion = promotion;
		this.restaurant = restaurant;
		this.code = code;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "promotion_lineitem_id", unique = true, nullable = false)
	public Long getPromotionLineitemId() {
		return this.promotionLineitemId;
	}

	public void setPromotionLineitemId(Long promotionLineitemId) {
		this.promotionLineitemId = promotionLineitemId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "promotion_id", nullable = false)
	public Promotion getPromotion() {
		return this.promotion;
	}

	public void setPromotion(Promotion promotion) {
		this.promotion = promotion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "restaurant_id", nullable = false)
	public Restaurant getRestaurant() {
		return this.restaurant;
	}

	public void setRestaurant(Restaurant restaurant) {
		this.restaurant = restaurant;
	}

	@Column(name = "code", length = 200)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

}
