package bmbsoft.orderfoodonline.entities;
// Generated May 17, 2018 3:10:44 PM by Hibernate Tools 5.2.8.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ResidenceType generated by hbm2java
 */
@Entity
@Table(name = "residence_type")
public class ResidenceType implements java.io.Serializable {

	private Long residenceTypeId;
	private ContentDefinition contentDefinition;
	private String name;
	private Integer status;
	private String residenceCode;

	public ResidenceType() {
	}

	public ResidenceType(String residenceCode) {
		this.residenceCode = residenceCode;
	}

	public ResidenceType(ContentDefinition contentDefinition, String name, Integer status, String residenceCode) {
		this.contentDefinition = contentDefinition;
		this.name = name;
		this.status = status;
		this.residenceCode = residenceCode;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "residence_type_id", unique = true, nullable = false)
	public Long getResidenceTypeId() {
		return this.residenceTypeId;
	}

	public void setResidenceTypeId(Long residenceTypeId) {
		this.residenceTypeId = residenceTypeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "content_dep_id")
	public ContentDefinition getContentDefinition() {
		return this.contentDefinition;
	}

	public void setContentDefinition(ContentDefinition contentDefinition) {
		this.contentDefinition = contentDefinition;
	}

	@Column(name = "name", length = 200)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "residence_code", nullable = false)
	public String getResidenceCode() {
		return this.residenceCode;
	}

	public void setResidenceCode(String residenceCode) {
		this.residenceCode = residenceCode;
	}

}
