package bmbsoft.orderfoodonline.entities;
// Generated Apr 22, 2018 10:51:03 PM by Hibernate Tools 5.2.8.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RestaurantFoodType generated by hbm2java
 */
@Entity
@Table(name = "restaurant_food_type", catalog = "ofo")
public class RestaurantFoodType implements java.io.Serializable {

	private long restaurantId;
	private FoodType foodType;

	public RestaurantFoodType() {
	}

	public RestaurantFoodType(long restaurantId, FoodType foodType) {
		this.restaurantId = restaurantId;
		this.foodType = foodType;
	}

	@Id

	@Column(name = "restaurant_id", unique = true, nullable = false)
	public long getRestaurantId() {
		return this.restaurantId;
	}

	public void setRestaurantId(long restaurantId) {
		this.restaurantId = restaurantId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "food_type_id", nullable = false)
	public FoodType getFoodType() {
		return this.foodType;
	}

	public void setFoodType(FoodType foodType) {
		this.foodType = foodType;
	}

}
