package bmbsoft.orderfoodonline.entities;
// Generated Sep 18, 2018 12:33:50 AM by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RestaurantPaymentProvider generated by hbm2java
 */
@Entity
@Table(name = "restaurant_payment_provider", catalog = "ofo")
public class RestaurantPaymentProvider implements java.io.Serializable {

	private Long restaurantPaymentId;
	private PaymentProvider paymentProvider;
	private Restaurant restaurant;

	public RestaurantPaymentProvider() {
	}

	public RestaurantPaymentProvider(PaymentProvider paymentProvider, Restaurant restaurant) {
		this.paymentProvider = paymentProvider;
		this.restaurant = restaurant;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "restaurant_payment_id", unique = true, nullable = false)
	public Long getRestaurantPaymentId() {
		return this.restaurantPaymentId;
	}

	public void setRestaurantPaymentId(Long restaurantPaymentId) {
		this.restaurantPaymentId = restaurantPaymentId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "payment_provider_id", nullable = false)
	public PaymentProvider getPaymentProvider() {
		return this.paymentProvider;
	}

	public void setPaymentProvider(PaymentProvider paymentProvider) {
		this.paymentProvider = paymentProvider;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "restaurant_id", nullable = false)
	public Restaurant getRestaurant() {
		return this.restaurant;
	}

	public void setRestaurant(Restaurant restaurant) {
		this.restaurant = restaurant;
	}

}
