package bmbsoft.orderfoodonline.entities;
// Generated Sep 18, 2018 12:33:50 AM by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RestaurantAttribute generated by hbm2java
 */
@Entity
@Table(name = "restaurant_attribute", catalog = "ofo")
public class RestaurantAttribute implements java.io.Serializable {

	private Long restaurantAttributeId;
	private Attribute attribute;
	private Restaurant restaurant;

	public RestaurantAttribute() {
	}

	public RestaurantAttribute(Attribute attribute, Restaurant restaurant) {
		this.attribute = attribute;
		this.restaurant = restaurant;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "restaurant_attribute_id", unique = true, nullable = false)
	public Long getRestaurantAttributeId() {
		return this.restaurantAttributeId;
	}

	public void setRestaurantAttributeId(Long restaurantAttributeId) {
		this.restaurantAttributeId = restaurantAttributeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "attribute_id", nullable = false)
	public Attribute getAttribute() {
		return this.attribute;
	}

	public void setAttribute(Attribute attribute) {
		this.attribute = attribute;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "restaurant_id", nullable = false)
	public Restaurant getRestaurant() {
		return this.restaurant;
	}

	public void setRestaurant(Restaurant restaurant) {
		this.restaurant = restaurant;
	}

}
