package bmbsoft.orderfoodonline.entities;
// Generated Sep 18, 2018 12:33:50 AM by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RoleModule generated by hbm2java
 */
@Entity
@Table(name = "role_module")
public class RoleModule implements java.io.Serializable {

	private Long roleModuleId;
	private ModuleAction moduleAction;
	private Role role;
	private UserRestaurant userRestaurant;

	public RoleModule() {
	}

	public RoleModule(ModuleAction moduleAction, Role role, UserRestaurant userRestaurant) {
		this.moduleAction = moduleAction;
		this.role = role;
		this.userRestaurant = userRestaurant;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "role_module_id", unique = true, nullable = false)
	public Long getRoleModuleId() {
		return this.roleModuleId;
	}

	public void setRoleModuleId(Long roleModuleId) {
		this.roleModuleId = roleModuleId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "module_action_id")
	public ModuleAction getModuleAction() {
		return this.moduleAction;
	}

	public void setModuleAction(ModuleAction moduleAction) {
		this.moduleAction = moduleAction;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "role_id")
	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_restaurant_id")
	public UserRestaurant getUserRestaurant() {
		return this.userRestaurant;
	}

	public void setUserRestaurant(UserRestaurant userRestaurant) {
		this.userRestaurant = userRestaurant;
	}

}
