package bmbsoft.orderfoodonline.entities;
// Generated Sep 18, 2018 12:33:50 AM by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SmtpConfig generated by hbm2java
 */
@Entity
@Table(name = "smtp_config", catalog = "ofo")
public class SmtpConfig implements java.io.Serializable {

	private long smtpId;
	private String smtpConfig;

	public SmtpConfig() {
	}

	public SmtpConfig(long smtpId) {
		this.smtpId = smtpId;
	}

	public SmtpConfig(long smtpId, String smtpConfig) {
		this.smtpId = smtpId;
		this.smtpConfig = smtpConfig;
	}

	@Id

	@Column(name = "smtp_id", unique = true, nullable = false)
	public long getSmtpId() {
		return this.smtpId;
	}

	public void setSmtpId(long smtpId) {
		this.smtpId = smtpId;
	}

	@Column(name = "smtp_config", length = 45)
	public String getSmtpConfig() {
		return this.smtpConfig;
	}

	public void setSmtpConfig(String smtpConfig) {
		this.smtpConfig = smtpConfig;
	}

}
