package bmbsoft.orderfoodonline.entities;
// Generated Sep 18, 2018 12:33:50 AM by Hibernate Tools 5.2.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tax generated by hbm2java
 */
@Entity
@Table(name = "tax")
public class Tax implements java.io.Serializable {

	private long taxId;
	private String name;
	private Integer value;
	private Date startDate;
	private Date endDate;

	public Tax() {
	}

	public Tax(long taxId) {
		this.taxId = taxId;
	}

	public Tax(long taxId, String name, Integer value, Date startDate, Date endDate) {
		this.taxId = taxId;
		this.name = name;
		this.value = value;
		this.startDate = startDate;
		this.endDate = endDate;
	}

	@Id

	@Column(name = "tax_id", unique = true, nullable = false)
	public long getTaxId() {
		return this.taxId;
	}

	public void setTaxId(long taxId) {
		this.taxId = taxId;
	}

	@Column(name = "name", length = 200)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "value")
	public Integer getValue() {
		return this.value;
	}

	public void setValue(Integer value) {
		this.value = value;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "start_date", length = 19)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "end_date", length = 19)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

}
