package bmbsoft.orderfoodonline.entities;
// Generated Sep 18, 2018 12:33:50 AM by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UserInfo generated by hbm2java
 */
@Entity
@Table(name = "user_info")
public class UserInfo implements java.io.Serializable {

	private Long userInfoId;
	private User user;
	private String emergencyNumber1;
	private String emergencyNumber2;
	private String contactName;
	private String email;
	private String website;

	public UserInfo() {
	}

	public UserInfo(User user, String emergencyNumber1, String emergencyNumber2, String contactName, String email,
			String website) {
		this.user = user;
		this.emergencyNumber1 = emergencyNumber1;
		this.emergencyNumber2 = emergencyNumber2;
		this.contactName = contactName;
		this.email = email;
		this.website = website;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "user_info_id", unique = true, nullable = false)
	public Long getUserInfoId() {
		return this.userInfoId;
	}

	public void setUserInfoId(Long userInfoId) {
		this.userInfoId = userInfoId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "emergency_number1")
	public String getEmergencyNumber1() {
		return this.emergencyNumber1;
	}

	public void setEmergencyNumber1(String emergencyNumber1) {
		this.emergencyNumber1 = emergencyNumber1;
	}

	@Column(name = "emergency_number2")
	public String getEmergencyNumber2() {
		return this.emergencyNumber2;
	}

	public void setEmergencyNumber2(String emergencyNumber2) {
		this.emergencyNumber2 = emergencyNumber2;
	}

	@Column(name = "contact_name")
	public String getContactName() {
		return this.contactName;
	}

	public void setContactName(String contactName) {
		this.contactName = contactName;
	}

	@Column(name = "email")
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "website")
	public String getWebsite() {
		return this.website;
	}

	public void setWebsite(String website) {
		this.website = website;
	}

}
