package bmbsoft.orderfoodonline.entities;
// Generated Sep 18, 2018 12:33:50 AM by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * UserRestaurant generated by hbm2java
 */
@Entity
@Table(name = "user_restaurant")
public class UserRestaurant implements java.io.Serializable {

	private Long userResId;
	private Restaurant restaurant;
	private User user;
	private Set<RoleModule> roleModules = new HashSet<RoleModule>(0);

	public UserRestaurant() {
	}

	public UserRestaurant(Restaurant restaurant, User user) {
		this.restaurant = restaurant;
		this.user = user;
	}

	public UserRestaurant(Restaurant restaurant, User user, Set<RoleModule> roleModules) {
		this.restaurant = restaurant;
		this.user = user;
		this.roleModules = roleModules;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "user_res_id", unique = true, nullable = false)
	public Long getUserResId() {
		return this.userResId;
	}

	public void setUserResId(Long userResId) {
		this.userResId = userResId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "restaurant_id", nullable = false)
	public Restaurant getRestaurant() {
		return this.restaurant;
	}

	public void setRestaurant(Restaurant restaurant) {
		this.restaurant = restaurant;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userRestaurant")
	public Set<RoleModule> getRoleModules() {
		return this.roleModules;
	}

	public void setRoleModules(Set<RoleModule> roleModules) {
		this.roleModules = roleModules;
	}

}
